[package]
name = "rust-miller-rabin"
version = "0.1.4"
edition = "2018"
description = "A Rust implementation of the Miller-Rabin primality test"
license = "MIT"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1.46"
num-traits = "0.2"
