[package]
name = "rust-miller-rabin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-integer = "0.1.46"
num-traits = "0.2"
rand = "0.8"
